config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  
  resources :sessions, only: [:create, :destroy]
  get 'home/index'
  
  resources :posts do
    resources :comments
  end
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :game_username, presence: true, length: { minimum: 2 }
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :delete_all
    validates :title, presence: true, length: { minimum: 2 }
    validates :title_of_the_game, presence: true, length: { minimum: 2 }
    validates :game_username, presence: true, length: { minimum: 2 }
    validates :text, presence: true, length: { minimum: 10 }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ApplicationRecord
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find_by_id(params[:post_id])
        @comment = @post.comments.create(comment_params)
        # @comment.commenter = current_user.name
        @comment.date = Time.now
        redirect_to post_path(@post)
    end
    
    def destroy
        @comment = Post.find_by_id(params[:post_id])
        @comment.destroy
        
        redirect_to posts_path
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :game_username, :body)
        end
end

app/controllers/comments_controller_backup.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @comment.date = (Time.now)
        redirect_to post_path(@post)
    end
    private
        def comment_params
            params.require(:comment).permit(:game_username, :body)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.poster_name = current_user.name
        @post.poster_id = current_user.id
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to posts_path
    end
end

private
    def post_params
        params.require(:post).permit(:title, :title_of_the_game, :game_username, :poster_name, :poster_id, :text)
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to posts_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def owner?(id)
        if current_user.id == id
            return true
        else
            return false
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/_design.html.erb
<head>
        <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
</head>
<header>
    
   
  
   
   
   <h1 id = "banner">GAME TOGETHER</h1>
</header>
<body>
    <div class = "container">
        
   
        
    </div>
</body>

app/views/home/index.html.erb
<%= render 'design' %>
<head>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
</head>


<h1 id = "listing">Home Page</h1>
<%= link_to 'Game Posts', controller: 'posts', id: "posts" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "sign">
      <% if current_user %>
        <label id = "username">Signed in as <strong><%= current_user.name %></strong>!</label>
        <%= link_to "Sign out", signout_path, id: "sign out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_design.html.erb
<head>
        <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
</head>
<header>
    
   
   
   
   <h1 id = "banner">GAME TOGETHER</h1>
</header>
<body>
      <div class = "container" id = "postpage">
        
   
        
    </div>
</body>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class = "postContainer">
  <p>
    <%= f.label :title, class: "postsub" %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :title_of_the_game, class: "postsub" %><br>
    <%= f.text_field :title_of_the_game %>
  </p>
  
  <p>
    <%= f.label :game_username, class: "postsub" %><br>
    <%= f.text_field :game_username %>
  </p>
 
  <p>
    <%= f.label :text, class: "postsub" %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    
    
  
    <%= form_for @post do |f| %>
    
      
  <%= f.button :submit => "", class: "submit", id: "newsubmit" %>
    <% end %>
  </p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'design' %>
<head>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
</head>
<h1 id = "listing">Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'design' %>
<head>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <h1 id = "listing">Listing posts</h1>


<% if current_user %>
  <%= link_to 'New post', new_post_path %>
<% else %>
  <%= link_to 'Log in to create post', posts_path %>
<% end %>
<!--<%= button_to "New post", new_post_path, :class => "button", :method => :get, id: 'button' %>-->
<div class = tableContainer>
<table id = "gamePost">
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Game Title</th>
    <!-- <th>Text</th> -->
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      
      <td id = "tableCell"><%= link_to post.title, post_path(post) %></td>
      <td id = "tableCell"><%= post.poster_name %></td>
      <td id = "tableCell"><%= post.title_of_the_game %></td>
      <!-- <td id = "tableCell"><%= link_to post.text, post_path(post) %></td> -->
    </tr>
  <% end %>
</table>
</div>

app/views/posts/new.html.erb
<%= render 'design' %>
<head>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
</head>
<div id = "block"></div>
<h1 id = "listing">New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'design' %>

<div class = "postContainer" id = "commentbox">
    
<div class = "divider" id = "postContainer1">
    <div class = "divider" id = "titleContainer">       
<h3 id = "postTitle"><%= @post.title %></h3>
</div>
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Game Title:</strong>
    <%= @post.title_of_the_game %>
</p>

<p>
    <strong>Username:</strong>
    <%= @post.poster_name %>
</p>

<% if current_user %>
    <% if (current_user.id.to_s.strip == @post.poster_id.to_s.strip) %>
        <p>
            <strong>Game Username:</strong>
            <%= @post.game_username %>
        </p>
    <% else %>
        <p> <b>Game Username: </b> <i>Only the topic poster can see game usernames</i></p>
    <% end %>
<% else %>
<p> <b>Game Username: </b> <i>Only the topic poster can see game usernames</i></p>
<% end %>

    <br>
    <br>
<p>
    
    <%= @post.text %>
</p>

<% if current_user %>
    <% if (current_user.id.to_s.strip == @post.poster_id.to_s.strip) %>
        <p>
        <%= link_to 'Edit', edit_post_path(@post), class: "action" %></td>
        &nbsp;
        <span class="action">-</span> 
        &nbsp;
        <%= link_to 'Delete', 
                    post_path(@post),
                    :confirm => 'Are you sure?',
                    method: :delete,
                    data: { confirm: 'Are you sure?' } ,class: "action", id: "delete" %></td>
        </p>
    <% end %>
<% end %>
</div>

    <br>
    <br>
    <br>
    <br>
    
<div class = "divider">
    <div class = "divider" id = "titleContainer">      
<h2>Comments</h2>
</div>
<% @post.comments.each do |comment| %>
    <% if current_user %>
        <% if (current_user.id.to_s.strip == @post.poster_id.to_s.strip) %>
        <p>
            <strong>Game Username:</strong>
            <%= comment.game_username %>
        </p>
        <% else %>
       <p> <b>Game Username: </b> <i>Only the topic poster can see game usernames</i></p>
        <% end %>
    <% else %>
    <p> <b>Game Username: </b> <i>Only the topic poster can see game usernames</i></p>
    <% end %>
    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>
    <br>
    <br>
<% end %>
</div>


    <br>
    <br>
    <br>
<div class = "divider">
    <div class = "divider" id = "titleContainer">     
<h2>Add a comment</h2>
</div>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :game_username %> <br>
        <%= f.text_field :game_username %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    
    <p>
        <br>
        <%= f.button :submit => "", class: "submit" %>
    </p>
<% end %>
</div>


</div>
<%= link_to 'Post List', posts_path %>